import { requireRole } from '@/lib/auth';
import { getComboOffer, getEnrollmentApplications, getEnrollmentGuide } from '@/lib/api/enrollments';
import { formatCoursePrice } from '@/lib/course-pricing';
import { EnrollmentReviewButtons } from '@/components/lms/enrollment-review-buttons';
import { EnrollmentVideoForm } from '@/components/lms/enrollment-video-form';
import { ComboOfferForm } from '@/components/lms/combo-offer-form';
import { PageHeader } from '@/components/lms/page-header';
export const metadata={title:'Enrollment requests'};
export default async function EnrollmentRequestsPage(){await requireRole('content_manager');const[rows,guide,offer]=await Promise.all([getEnrollmentApplications(),getEnrollmentGuide().catch(()=>null),getComboOffer()]);return <div className="mx-auto max-w-5xl"><PageHeader eyebrow="Content Manager" title="Enrollment requests" description="Verify payment details before granting course access."/><ComboOfferForm offer={offer!}/><EnrollmentVideoForm initialUrl={guide?.videoUrl}/><div className="space-y-4">{rows.map(row=><article key={row.documentId} className="rounded-xl border bg-card p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div className="min-w-0 break-words"><h2 className="font-semibold">{row.name}</h2><p className="text-sm text-muted-foreground">{row.email} · {row.phone}</p><p className="mt-2 text-sm">{row.courseSummary.map(c=>c.title).join(', ')}</p><p className="mt-1 text-sm">{row.paymentMethod.toUpperCase()} · Transaction: <b>{row.transactionId}</b>{Number(row.comboDiscount)>0&&<> · Combo saved: <b>{formatCoursePrice(Number(row.comboDiscount))}</b></>} · Total: <b>{formatCoursePrice(Number(row.totalAmount))}</b></p></div><div className="shrink-0"><span className="mb-3 block text-sm font-semibold capitalize">{row.status}</span>{row.status==='pending'&&<EnrollmentReviewButtons id={row.documentId}/>}</div></div></article>)}{!rows.length&&<p className="text-sm text-muted-foreground">No enrollment applications yet.</p>}</div></div>}
