'use client';
import { useMemo, useState, useTransition } from 'react';
import { toast } from 'sonner';
import { CircleCheck } from 'lucide-react';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label';
import { submitEnrollmentApplicationAction } from '@/app/actions/enrollment';
import { discountedPrice, formatCoursePrice } from '@/lib/course-pricing'; import type { ComboOffer, Course, SessionUser } from '@/types/lms';
export function EnrollmentApplicationForm({courses,user,comboOffer,isLoyal,initialSlug}:{courses:Course[];user:SessionUser;comboOffer:ComboOffer;isLoyal:boolean;initialSlug?:string}) {
  const [selected,setSelected]=useState(() => new Set(courses.filter(c=>c.slug===initialSlug).map(c=>c.documentId))); const [pending,start]=useTransition(); const [submitted,setSubmitted]=useState(false);
  const subtotal=useMemo(()=>courses.filter(c=>selected.has(c.documentId)).reduce((s,c)=>s+discountedPrice(Number(c.price),Number(c.discountPercent)),0),[courses,selected]);
  const comboDiscount=comboOffer.isActive?comboOffer.tiers.reduce((best,tier)=>selected.size>=tier.courseCount?Math.max(best,tier.discountAmount):best,0):0;
  const loyaltyDiscount=comboOffer.isActive&&isLoyal?Math.min(Math.max(0,subtotal-comboDiscount),comboOffer.loyaltyDiscount):0;
  const total=Math.max(0,subtotal-comboDiscount-loyaltyDiscount);
  function toggle(id:string){setSelected(old=>{const n=new Set(old);if(n.has(id))n.delete(id);else n.add(id);return n;});}
  if(submitted)return <div role="status" className="rounded-xl border border-pine/30 bg-pine-wash p-8 text-center"><CircleCheck className="mx-auto size-10 text-pine" aria-hidden/><h2 className="mt-4 text-xl font-semibold">Information sent successfully</h2><p className="mx-auto mt-2 max-w-lg text-sm text-muted-foreground">Your enrollment information has been sent to the Content Manager. You will receive course access after the payment and application are approved.</p></div>;
  return <form className="space-y-8" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);start(async()=>{const result=await submitEnrollmentApplicationAction(f,[...selected]);if(result.ok){toast.success('Information sent to the Content Manager');setSubmitted(true);}else toast.error(result.error);});}}>
    <section className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="min-w-0 rounded-xl border bg-card p-4 sm:p-5"><h2 className="text-lg font-semibold">Select courses</h2><div className="mt-4 space-y-3">{courses.map(c=><label key={c.documentId} className="flex cursor-pointer flex-col items-start gap-2 rounded-lg border p-3 min-[420px]:flex-row min-[420px]:items-center min-[420px]:justify-between"><span className="flex min-w-0 items-start gap-3"><input className="mt-1 shrink-0" type="checkbox" checked={selected.has(c.documentId)} onChange={()=>toggle(c.documentId)}/><span className="break-words">{c.title}</span></span><b className="shrink-0 pl-7 min-[420px]:pl-0">{formatCoursePrice(discountedPrice(Number(c.price),Number(c.discountPercent)))}</b></label>)}</div></div><aside className="rounded-xl border bg-card p-4 sm:p-5"><h2 className="font-semibold">Price summary</h2><dl className="mt-6 space-y-2 text-sm"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Subtotal</dt><dd>{formatCoursePrice(subtotal)}</dd></div>{comboDiscount>0&&<div className="flex justify-between gap-3 text-pine"><dt>Combo discount</dt><dd>− {formatCoursePrice(Math.min(subtotal,comboDiscount))}</dd></div>}{loyaltyDiscount>0&&<div className="flex justify-between gap-3 text-pine"><dt>Loyalty discount</dt><dd>− {formatCoursePrice(loyaltyDiscount)}</dd></div>}</dl><p className="mt-5 text-sm text-muted-foreground">Total amount</p><p className="mt-1 text-2xl font-bold text-pine sm:text-3xl">{formatCoursePrice(total)}</p></aside></section>
    <section className="rounded-xl border bg-card p-4 sm:p-5"><div className="flex flex-col items-start gap-1 sm:flex-row sm:items-center sm:justify-between sm:gap-3"><h2 className="text-lg font-semibold">Basic and payment information</h2><p className="text-xs text-destructive">* All fields are required</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{[['name','Name',user.username],['email','Email',user.email],['phone','Mobile number',''],['discord','Discord account',''],['institution','Institution name','']].map(([name,label,value])=><div className="min-w-0 space-y-2" key={name}><Label htmlFor={name}>{label} <span className="text-destructive">*</span></Label><Input id={name} name={name} type={name==='email'?'email':name==='phone'?'tel':'text'} defaultValue={value} required aria-required="true"/></div>)}<div className="min-w-0 space-y-2"><Label htmlFor="paymentProof">Payment picture <span className="text-destructive">*</span></Label><Input id="paymentProof" name="paymentProof" type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif,image/heic,image/heif" required aria-required="true"/><p className="text-xs text-muted-foreground">JPG, PNG, WebP, GIF, AVIF, HEIC, or HEIF. Maximum 5 MB.</p></div><div className="min-w-0 space-y-2"><Label htmlFor="paymentMethod">Payment method <span className="text-destructive">*</span></Label><select id="paymentMethod" name="paymentMethod" required aria-required="true" className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="">Select payment method</option><option value="bkash">bKash</option><option value="rocket">Rocket</option><option value="nagad">Nagad</option></select></div><div className="min-w-0 space-y-2"><Label>Total amount</Label><Input value={formatCoursePrice(total)} readOnly /></div></div></section><Button className="w-full sm:w-auto" type="submit" size="lg" disabled={pending||!selected.size}>{pending?'Uploading…':'Submit Information'}</Button>
  </form>;
}
