'use client';
import { useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label';
import { submitEnrollmentApplicationAction } from '@/app/actions/enrollment';
import { discountedPrice, formatCoursePrice } from '@/lib/course-pricing'; import type { Course, SessionUser } from '@/types/lms';
export function EnrollmentApplicationForm({courses,user,initialSlug}:{courses:Course[];user:SessionUser;initialSlug?:string}) {
  const [selected,setSelected]=useState(() => new Set(courses.filter(c=>c.slug===initialSlug).map(c=>c.documentId))); const [pending,start]=useTransition(); const router=useRouter();
  const total=useMemo(()=>courses.filter(c=>selected.has(c.documentId)).reduce((s,c)=>s+discountedPrice(Number(c.price),Number(c.discountPercent)),0),[courses,selected]);
  function toggle(id:string){setSelected(old=>{const n=new Set(old);if(n.has(id))n.delete(id);else n.add(id);return n;});}
  return <form className="space-y-8" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);start(async()=>{const result=await submitEnrollmentApplicationAction({courseIds:[...selected],name:f.get('name'),email:f.get('email'),phone:f.get('phone'),discord:f.get('discord'),institution:f.get('institution'),paymentMethod:f.get('paymentMethod'),transactionId:f.get('transactionId')});if(result.ok){toast.success('Application sent for admin approval');router.push('/');router.refresh();}else toast.error(result.error);});}}>
    <section className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border bg-card p-5"><h2 className="text-lg font-semibold">Select courses</h2><div className="mt-4 space-y-3">{courses.map(c=><label key={c.documentId} className="flex cursor-pointer items-center justify-between gap-3 rounded-lg border p-3"><span className="flex items-center gap-3"><input type="checkbox" checked={selected.has(c.documentId)} onChange={()=>toggle(c.documentId)}/><span>{c.title}</span></span><b>{formatCoursePrice(discountedPrice(Number(c.price),Number(c.discountPercent)))}</b></label>)}</div></div><aside className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Price summary</h2><p className="mt-8 text-sm text-muted-foreground">Total amount</p><p className="mt-1 text-3xl font-bold text-pine">{formatCoursePrice(total)}</p></aside></section>
    <section className="rounded-xl border bg-card p-5"><h2 className="text-lg font-semibold">Basic and payment information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[['name','Name',user.username],['email','Email',user.email],['phone','Mobile number',''],['discord','Discord account',''],['institution','Institution name',''],['transactionId','Transaction ID','']].map(([name,label,value])=><div className="space-y-2" key={name}><Label htmlFor={name}>{label}</Label><Input id={name} name={name} defaultValue={value} required={['name','email','phone','transactionId'].includes(name)}/></div>)}<div className="space-y-2"><Label htmlFor="paymentMethod">Payment method</Label><select id="paymentMethod" name="paymentMethod" required className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="bkash">bKash</option><option value="rocket">Rocket</option><option value="nagad">Nagad</option></select></div><div className="space-y-2"><Label>Total amount</Label><Input value={formatCoursePrice(total)} readOnly /></div></div></section><Button size="lg" disabled={pending||!selected.size}>{pending?'Submitting…':'Submit for admin approval'}</Button>
  </form>;
}
